---
- hosts: raspi
  gather_facts: no
  vars_prompt:
  - name: ansible_host
    prompt: Remote host address?
    private: no

  tasks:
  - name: check if remote host is reachable
    wait_for_connection:
      timeout: 5
    register: user_reachable
    failed_when: false
    changed_when: user_reachable is failed
  
  - name: set ansible_host
    set_fact:
      ansible_host: "{{ ansible_host }}"
    when: user_reachable is not changed

  - name: add remote host to inventory
    add_host:
      name: raspi
      ansible_host: "{{ ansible_host }}"
      ansible_user: "{{ account.username }}"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    when: user_reachable is changed


# Copy template
- import_playbook: setup/template.yml

# Setup account
- import_playbook: setup/account.yml
  when: user_reachable is not changed

# Setup public key authentication
- import_playbook: setup/keypair.yml

# Setup SSH daemon
- import_playbook: setup/ssh.yml
